name: Byg og Push Docker Image

# Hvornår skal robotten køre?
on:
  push:
    branches: [ "main" ]
    # Vi beder den ignorere ændringer i k8s-mappen
    paths-ignore:
      - 'k8s/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest # Robotten er en frisk Linux-maskine hos GitHub

    steps:
    - name: 1. Hent koden fra GitHub
      uses: actions/checkout@v3

    - name: 2. Log ind på Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 3. Byg og Push image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: andrewsher2026/dogapi:latest
